# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e1bd5a76384f1cb2c103f207eb7adeb58e1d27f1b244e7dc6d17442bd8460974579e75f7c13d605a58a09b676e51d0391f098f99bb6229f9c4b61e1b90d060d6

test:
  secret_key_base: 5a5136958025529328eb5fc6e8c1ae3c93386f8c8107af869be4471d55ff66be22744df4c19d20d70c5b147f2674ab818b62cbf70ed5ddd0aa7e5a43afe8af17

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
